# Generated by Django 6.0.2 on 2026-03-02 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_remove_payment_paid_at_payment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Fornecedor')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantidade em Stock')),
                ('min_stock_alert', models.IntegerField(default=5, verbose_name='Alerta Stock Baixo')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='professional_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comissão do Profissional'),
        ),
        migrations.AddField(
            model_name='professional',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taxa de Comissão (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Notas Internas'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.TextField(blank=True, verbose_name='Preferências'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('transfer', 'Transferência Bancária')], default='cash', max_length=20, verbose_name='Método'),
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Avaliação')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out_service', 'Saída (Serviço)'), ('out_manual', 'Saída Manual')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_off', models.BooleanField(default=False, verbose_name='Folga')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='core.professional')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
                'unique_together': {('professional', 'day')},
            },
        ),
    ]
