# Generated by Django 6.0.2 on 2026-03-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_payment_professional_commission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade Consumida')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_products', to='core.service')),
            ],
        ),
    ]
